[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
enableWebsocketCompression = false
heartbeatTimeout = 300  # <--- [핵심] 300초(5분) 동안은 끊지 말고 기다려!

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
